import type { Course, Provider } from '@/types';

export const providers: Provider[] = [
  {
    id: 'prov_1',
    slug: 'coursera',
    name: 'Coursera',
    description: 'Online courses from top universities',
    website: 'https://coursera.org',
  },
  {
    id: 'prov_2',
    slug: 'udemy',
    name: 'Udemy',
    description: 'Learn on demand',
    website: 'https://udemy.com',
  },
];

export const courses: Course[] = [
  {
    id: 'course_1',
    slug: 'intro-to-typescript',
    title: 'Introduction to TypeScript',
    description: 'Learn TypeScript from scratch with hands-on projects.',
    shortDescription: 'Master TypeScript fundamentals',
    providerId: 'prov_1',
    providerCourseId: 'ts-101',
    providerUrl: 'https://coursera.org/learn/typescript',
    instructors: ['John Doe'],
    level: 'beginner',
    status: 'published',
    duration: { hours: 12, minutes: 30 },
    price: { amount: 0, currency: 'USD', isFree: true },
    topics: ['TypeScript', 'JavaScript', 'Web Development'],
    skills: ['Type Safety', 'Static Typing', 'Interfaces'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'es'],
      lastUpdated: '2024-12-01',
      enrollmentCount: 50000,
      rating: 4.8,
      reviewCount: 1200,
    },
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'course_2',
    slug: 'advanced-react-patterns',
    title: 'Advanced React Patterns',
    description:
      'Deep dive into advanced React patterns and performance optimization.',
    shortDescription: 'Level up your React skills',
    providerId: 'prov_2',
    providerCourseId: 'react-adv',
    providerUrl: 'https://udemy.com/course/react-patterns',
    instructors: ['Jane Smith', 'Bob Wilson'],
    level: 'advanced',
    status: 'published',
    duration: { hours: 24, minutes: 0 },
    price: { amount: 89.99, currency: 'USD', isFree: false },
    topics: ['React', 'JavaScript', 'Frontend'],
    skills: ['Component Patterns', 'Performance', 'State Management'],
    metadata: {
      language: 'en',
      subtitles: ['en'],
      lastUpdated: '2024-11-15',
      enrollmentCount: 25000,
      rating: 4.9,
      reviewCount: 800,
    },
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
];
