import type { Course, Provider } from '@/types';

export const providers: Provider[] = [
  {
    id: 'prov_1',
    slug: 'coursera',
    name: 'Coursera',
    description: 'Online courses from top universities',
    website: 'https://coursera.org',
  },
  {
    id: 'prov_2',
    slug: 'udemy',
    name: 'Udemy',
    description: 'Learn on demand',
    website: 'https://udemy.com',
  },
  {
    id: 'prov_3',
    slug: 'edx',
    name: 'edX',
    description: 'Free online courses from top institutions',
    website: 'https://edx.org',
  },
  {
    id: 'prov_4',
    slug: 'pluralsight',
    name: 'Pluralsight',
    description: 'Technology skills platform',
    website: 'https://pluralsight.com',
  },
  {
    id: 'prov_5',
    slug: 'linkedin-learning',
    name: 'LinkedIn Learning',
    description: 'Business, tech, and creative skills',
    website: 'https://linkedin.com/learning',
  },
];

export const courses: Course[] = [
  {
    id: 'course_1',
    slug: 'intro-to-typescript',
    title: 'Introduction to TypeScript',
    description:
      'Learn TypeScript from scratch with hands-on projects. This course covers type annotations, interfaces, generics, and how to integrate TypeScript into existing JavaScript projects.',
    shortDescription: 'Master TypeScript fundamentals',
    thumbnail: 'https://picsum.photos/seed/typescript/400/225',
    providerId: 'prov_1',
    providerCourseId: 'ts-101',
    providerUrl: 'https://coursera.org/learn/typescript',
    instructors: ['Dr. Sarah Chen'],
    level: 'beginner',
    status: 'published',
    duration: { hours: 12, minutes: 30 },
    price: { amount: 0, currency: 'USD', isFree: true },
    topics: ['TypeScript', 'JavaScript', 'Web Development'],
    skills: ['Type Safety', 'Static Typing', 'Interfaces', 'Generics'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'es', 'fr'],
      lastUpdated: '2025-01-10',
      enrollmentCount: 52000,
      rating: 4.8,
      reviewCount: 1240,
    },
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'course_2',
    slug: 'advanced-react-patterns',
    title: 'Advanced React Patterns',
    description:
      'Deep dive into advanced React patterns and performance optimization. Learn compound components, render props, custom hooks, and how to build scalable component libraries.',
    shortDescription: 'Level up your React architecture skills',
    thumbnail: 'https://picsum.photos/seed/react-patterns/400/225',
    providerId: 'prov_2',
    providerCourseId: 'react-adv',
    providerUrl: 'https://udemy.com/course/react-patterns',
    instructors: ['Jane Smith', 'Bob Wilson'],
    level: 'advanced',
    status: 'published',
    duration: { hours: 24, minutes: 0 },
    price: { amount: 89.99, currency: 'USD', isFree: false },
    topics: ['React', 'JavaScript', 'Frontend Architecture'],
    skills: ['Component Patterns', 'Performance Optimization', 'State Management'],
    metadata: {
      language: 'en',
      subtitles: ['en'],
      lastUpdated: '2025-01-05',
      enrollmentCount: 25000,
      rating: 4.9,
      reviewCount: 810,
    },
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'course_3',
    slug: 'python-for-data-science',
    title: 'Python for Data Science & Machine Learning',
    description:
      'Comprehensive course covering Python fundamentals, NumPy, Pandas, Matplotlib, Scikit-Learn, and TensorFlow. Build real-world data science projects from scratch.',
    shortDescription: 'From Python basics to ML models',
    thumbnail: 'https://picsum.photos/seed/python-ds/400/225',
    providerId: 'prov_1',
    providerCourseId: 'py-ds-201',
    providerUrl: 'https://coursera.org/learn/python-data-science',
    instructors: ['Prof. James Rodriguez', 'Dr. Aisha Patel'],
    level: 'intermediate',
    status: 'published',
    duration: { hours: 42, minutes: 15 },
    price: { amount: 49.99, currency: 'USD', isFree: false },
    topics: ['Python', 'Data Science', 'Machine Learning', 'Statistics'],
    skills: ['Data Analysis', 'Visualization', 'Predictive Modeling', 'Pandas'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'es', 'zh', 'hi'],
      lastUpdated: '2025-01-20',
      enrollmentCount: 134000,
      rating: 4.7,
      reviewCount: 4520,
    },
    createdAt: '2023-06-10T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'course_4',
    slug: 'full-stack-nextjs',
    title: 'Full-Stack Development with Next.js 15',
    description:
      'Build production-ready full-stack applications using Next.js 15, React Server Components, Server Actions, and Postgres. Deploy to Vercel with CI/CD.',
    shortDescription: 'Build and deploy full-stack Next.js apps',
    thumbnail: 'https://picsum.photos/seed/nextjs-full/400/225',
    providerId: 'prov_2',
    providerCourseId: 'next-fs-15',
    providerUrl: 'https://udemy.com/course/fullstack-nextjs',
    instructors: ['Maximilian Schwarzer'],
    level: 'intermediate',
    status: 'published',
    duration: { hours: 36, minutes: 45 },
    price: { amount: 94.99, currency: 'USD', isFree: false },
    topics: ['Next.js', 'React', 'Node.js', 'PostgreSQL', 'Full-Stack'],
    skills: ['Server Components', 'Server Actions', 'Database Design', 'Deployment'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'de', 'pt'],
      lastUpdated: '2025-01-18',
      enrollmentCount: 67000,
      rating: 4.8,
      reviewCount: 2100,
    },
    createdAt: '2024-05-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'course_5',
    slug: 'aws-cloud-practitioner',
    title: 'AWS Certified Cloud Practitioner',
    description:
      'Prepare for the AWS Cloud Practitioner certification exam. Covers core AWS services, pricing, security, architecture, and cloud concepts with practice exams.',
    shortDescription: 'Ace the AWS Cloud Practitioner exam',
    thumbnail: 'https://picsum.photos/seed/aws-cloud/400/225',
    providerId: 'prov_3',
    providerCourseId: 'aws-cp-001',
    providerUrl: 'https://edx.org/course/aws-cloud-practitioner',
    instructors: ['Michael Torres'],
    level: 'beginner',
    status: 'published',
    duration: { hours: 18, minutes: 0 },
    price: { amount: 0, currency: 'USD', isFree: true },
    topics: ['AWS', 'Cloud Computing', 'DevOps', 'Certification'],
    skills: ['Cloud Architecture', 'AWS Services', 'Security Fundamentals'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'es', 'ja'],
      lastUpdated: '2025-01-12',
      enrollmentCount: 98000,
      rating: 4.6,
      reviewCount: 3200,
    },
    createdAt: '2023-09-15T00:00:00Z',
    updatedAt: '2025-01-12T00:00:00Z',
  },
  {
    id: 'course_6',
    slug: 'ui-ux-design-fundamentals',
    title: 'UI/UX Design Fundamentals',
    description:
      'Learn the principles of user interface and user experience design. Master Figma, wireframing, prototyping, usability testing, and design systems.',
    shortDescription: 'Design beautiful, user-friendly interfaces',
    thumbnail: 'https://picsum.photos/seed/ui-ux/400/225',
    providerId: 'prov_5',
    providerCourseId: 'ux-101',
    providerUrl: 'https://linkedin.com/learning/ui-ux-fundamentals',
    instructors: ['Emily Nakamura', 'Carlos Rivera'],
    level: 'beginner',
    status: 'published',
    duration: { hours: 15, minutes: 20 },
    price: { amount: 29.99, currency: 'USD', isFree: false },
    topics: ['UI Design', 'UX Design', 'Figma', 'Prototyping'],
    skills: ['Wireframing', 'User Research', 'Design Systems', 'Accessibility'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'fr', 'ko'],
      lastUpdated: '2024-12-20',
      enrollmentCount: 45000,
      rating: 4.7,
      reviewCount: 1580,
    },
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-12-20T00:00:00Z',
  },
  {
    id: 'course_7',
    slug: 'docker-kubernetes-masterclass',
    title: 'Docker & Kubernetes Masterclass',
    description:
      'Master containerization with Docker and orchestration with Kubernetes. Covers Docker Compose, Helm charts, service meshes, monitoring, and production deployment strategies.',
    shortDescription: 'Containerize and orchestrate like a pro',
    thumbnail: 'https://picsum.photos/seed/docker-k8s/400/225',
    providerId: 'prov_4',
    providerCourseId: 'dk-master',
    providerUrl: 'https://pluralsight.com/courses/docker-kubernetes-masterclass',
    instructors: ['Nadia Kowalski'],
    level: 'intermediate',
    status: 'published',
    duration: { hours: 28, minutes: 30 },
    price: { amount: 44.99, currency: 'USD', isFree: false },
    topics: ['Docker', 'Kubernetes', 'DevOps', 'Cloud Infrastructure'],
    skills: ['Containerization', 'Orchestration', 'CI/CD', 'Helm'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'de'],
      lastUpdated: '2025-01-08',
      enrollmentCount: 38000,
      rating: 4.8,
      reviewCount: 1020,
    },
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2025-01-08T00:00:00Z',
  },
  {
    id: 'course_8',
    slug: 'rust-systems-programming',
    title: 'Rust for Systems Programming',
    description:
      'Learn Rust from the ground up. Covers ownership, borrowing, lifetimes, async/await, error handling, and building performant CLI tools and web servers.',
    shortDescription: 'Write safe, fast systems code with Rust',
    thumbnail: 'https://picsum.photos/seed/rust-lang/400/225',
    providerId: 'prov_3',
    providerCourseId: 'rust-sys-01',
    providerUrl: 'https://edx.org/course/rust-systems-programming',
    instructors: ['Dr. Henrik Larsson'],
    level: 'intermediate',
    status: 'published',
    duration: { hours: 30, minutes: 0 },
    price: { amount: 0, currency: 'USD', isFree: true },
    topics: ['Rust', 'Systems Programming', 'Concurrency', 'Memory Safety'],
    skills: ['Ownership Model', 'Async Programming', 'Error Handling', 'FFI'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'zh'],
      lastUpdated: '2025-01-15',
      enrollmentCount: 22000,
      rating: 4.9,
      reviewCount: 640,
    },
    createdAt: '2024-04-20T00:00:00Z',
    updatedAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'course_9',
    slug: 'sql-database-engineering',
    title: 'SQL & Database Engineering',
    description:
      'Master SQL from basics to advanced query optimization. Covers PostgreSQL, indexing strategies, transactions, database normalization, and schema design at scale.',
    shortDescription: 'Master SQL and database design',
    thumbnail: 'https://picsum.photos/seed/sql-db/400/225',
    providerId: 'prov_2',
    providerCourseId: 'sql-eng-301',
    providerUrl: 'https://udemy.com/course/sql-database-engineering',
    instructors: ['Priya Sharma', 'David Kim'],
    level: 'intermediate',
    status: 'published',
    duration: { hours: 20, minutes: 45 },
    price: { amount: 79.99, currency: 'USD', isFree: false },
    topics: ['SQL', 'PostgreSQL', 'Database Design', 'Query Optimization'],
    skills: ['Complex Queries', 'Indexing', 'Normalization', 'Performance Tuning'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'hi', 'es'],
      lastUpdated: '2024-12-28',
      enrollmentCount: 56000,
      rating: 4.7,
      reviewCount: 1890,
    },
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2024-12-28T00:00:00Z',
  },
  {
    id: 'course_10',
    slug: 'cybersecurity-essentials',
    title: 'Cybersecurity Essentials',
    description:
      'Build a strong foundation in cybersecurity. Learn network security, cryptography, vulnerability assessment, ethical hacking basics, and incident response.',
    shortDescription: 'Protect systems from modern threats',
    thumbnail: 'https://picsum.photos/seed/cybersec/400/225',
    providerId: 'prov_3',
    providerCourseId: 'cyber-101',
    providerUrl: 'https://edx.org/course/cybersecurity-essentials',
    instructors: ['Lt. Col. Rachel Foster (Ret.)'],
    level: 'beginner',
    status: 'published',
    duration: { hours: 22, minutes: 10 },
    price: { amount: 0, currency: 'USD', isFree: true },
    topics: ['Cybersecurity', 'Network Security', 'Cryptography', 'Ethical Hacking'],
    skills: ['Threat Analysis', 'Penetration Testing', 'Incident Response', 'Risk Assessment'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'ar', 'fr'],
      lastUpdated: '2025-01-22',
      enrollmentCount: 81000,
      rating: 4.6,
      reviewCount: 2750,
    },
    createdAt: '2023-08-15T00:00:00Z',
    updatedAt: '2025-01-22T00:00:00Z',
  },
  {
    id: 'course_11',
    slug: 'go-microservices',
    title: 'Building Microservices with Go',
    description:
      'Design and build production microservices in Go. Covers gRPC, REST APIs, message queues, distributed tracing, and deploying to Kubernetes.',
    shortDescription: 'Scalable microservices in Go',
    thumbnail: 'https://picsum.photos/seed/go-micro/400/225',
    providerId: 'prov_4',
    providerCourseId: 'go-ms-201',
    providerUrl: 'https://pluralsight.com/courses/go-microservices',
    instructors: ['Oluwaseun Adeyemi'],
    level: 'advanced',
    status: 'published',
    duration: { hours: 26, minutes: 15 },
    price: { amount: 59.99, currency: 'USD', isFree: false },
    topics: ['Go', 'Microservices', 'gRPC', 'Distributed Systems'],
    skills: ['API Design', 'Service Mesh', 'Message Queues', 'Observability'],
    metadata: {
      language: 'en',
      subtitles: ['en'],
      lastUpdated: '2025-01-02',
      enrollmentCount: 19000,
      rating: 4.8,
      reviewCount: 520,
    },
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'course_12',
    slug: 'mobile-dev-react-native',
    title: 'Mobile App Development with React Native',
    description:
      'Build cross-platform mobile apps with React Native. Covers navigation, native modules, animations, push notifications, and App Store / Play Store deployment.',
    shortDescription: 'Ship iOS & Android apps from one codebase',
    thumbnail: 'https://picsum.photos/seed/react-native/400/225',
    providerId: 'prov_2',
    providerCourseId: 'rn-mob-101',
    providerUrl: 'https://udemy.com/course/react-native-mobile',
    instructors: ['Fatima Al-Rashid', 'Stephen Burke'],
    level: 'intermediate',
    status: 'published',
    duration: { hours: 32, minutes: 0 },
    price: { amount: 84.99, currency: 'USD', isFree: false },
    topics: ['React Native', 'Mobile Development', 'iOS', 'Android'],
    skills: ['Cross-Platform Dev', 'Native Modules', 'App Deployment', 'Animations'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'ar', 'pt'],
      lastUpdated: '2024-12-15',
      enrollmentCount: 41000,
      rating: 4.6,
      reviewCount: 1350,
    },
    createdAt: '2024-02-28T00:00:00Z',
    updatedAt: '2024-12-15T00:00:00Z',
  },
  {
    id: 'course_13',
    slug: 'generative-ai-llms',
    title: 'Generative AI & Large Language Models',
    description:
      'Understand the theory and practice behind LLMs. Covers transformer architecture, fine-tuning, prompt engineering, RAG, and building AI-powered applications.',
    shortDescription: 'Build with cutting-edge AI models',
    thumbnail: 'https://picsum.photos/seed/gen-ai/400/225',
    providerId: 'prov_1',
    providerCourseId: 'ai-llm-301',
    providerUrl: 'https://coursera.org/learn/generative-ai-llms',
    instructors: ['Prof. Wei Zhang', 'Dr. Anna Kolesnikova'],
    level: 'advanced',
    status: 'published',
    duration: { hours: 38, minutes: 20 },
    price: { amount: 69.99, currency: 'USD', isFree: false },
    topics: ['AI', 'Large Language Models', 'NLP', 'Deep Learning'],
    skills: ['Prompt Engineering', 'Fine-Tuning', 'RAG', 'Transformer Architecture'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'zh', 'ja', 'ko'],
      lastUpdated: '2025-01-25',
      enrollmentCount: 112000,
      rating: 4.9,
      reviewCount: 3800,
    },
    createdAt: '2024-07-10T00:00:00Z',
    updatedAt: '2025-01-25T00:00:00Z',
  },
  {
    id: 'course_14',
    slug: 'git-version-control',
    title: 'Git & Version Control Mastery',
    description:
      'Go beyond the basics of Git. Learn branching strategies, rebasing, cherry-picking, bisect, worktrees, and team workflows for monorepos and open source.',
    shortDescription: 'Become a Git power user',
    thumbnail: 'https://picsum.photos/seed/git-vc/400/225',
    providerId: 'prov_5',
    providerCourseId: 'git-201',
    providerUrl: 'https://linkedin.com/learning/git-version-control',
    instructors: ['Marcus Thompson'],
    level: 'beginner',
    status: 'published',
    duration: { hours: 8, minutes: 45 },
    price: { amount: 19.99, currency: 'USD', isFree: false },
    topics: ['Git', 'Version Control', 'CI/CD', 'Collaboration'],
    skills: ['Branching Strategies', 'Rebasing', 'Code Review', 'Monorepo Management'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'es', 'de'],
      lastUpdated: '2024-11-30',
      enrollmentCount: 73000,
      rating: 4.7,
      reviewCount: 2400,
    },
    createdAt: '2023-10-01T00:00:00Z',
    updatedAt: '2024-11-30T00:00:00Z',
  },
  {
    id: 'course_15',
    slug: 'system-design-interview',
    title: 'System Design for Tech Interviews',
    description:
      'Prepare for system design interviews at top tech companies. Covers load balancers, caching, databases, message queues, CDNs, and designing systems like Twitter, Uber, and YouTube.',
    shortDescription: 'Crack the system design interview',
    thumbnail: 'https://picsum.photos/seed/sys-design/400/225',
    providerId: 'prov_4',
    providerCourseId: 'sd-int-401',
    providerUrl: 'https://pluralsight.com/courses/system-design-interview',
    instructors: ['Alex Xu', 'Sanjay Mehta'],
    level: 'advanced',
    status: 'published',
    duration: { hours: 16, minutes: 30 },
    price: { amount: 54.99, currency: 'USD', isFree: false },
    topics: ['System Design', 'Distributed Systems', 'Scalability', 'Architecture'],
    skills: ['Load Balancing', 'Caching', 'Database Sharding', 'API Design'],
    metadata: {
      language: 'en',
      subtitles: ['en', 'hi', 'zh'],
      lastUpdated: '2025-01-19',
      enrollmentCount: 89000,
      rating: 4.9,
      reviewCount: 3100,
    },
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2025-01-19T00:00:00Z',
  },
];
